//! GENERATED by scripts/gen-cldr-plurals.py from CLDR 48. Do not edit.
//! Cardinal/ordinal conditions and plural-range resolution for Lumen's supported locales.

#[allow(dead_code)]
#[derive(Clone, Copy)]
enum Operand { N, I, F, T, V, W, C, E }

#[derive(Clone, Copy)]
struct Operands<'a> {
    integer: &'a str,
    fraction: &'a str,
    fraction_trimmed: &'a str,
    compact_exponent: u32,
}

impl<'a> Operands<'a> {
    fn new(decimal: &'a str, compact_exponent: u32) -> Self {
        let decimal = decimal.strip_prefix(['+', '-']).unwrap_or(decimal);
        let (integer, fraction) = decimal.split_once('.').unwrap_or((decimal, ""));
        Self {
            integer: if integer.is_empty() { "0" } else { integer },
            fraction,
            fraction_trimmed: fraction.trim_end_matches('0'),
            compact_exponent,
        }
    }
}

fn digits_mod(digits: &str, modulus: u32) -> u32 {
    digits.bytes().fold(0, |value, digit|
        (value * 10 + u32::from(digit - b'0')) % modulus)
}

fn digits_in_ranges(digits: &str, modulus: u32, ranges: &[(u32, u32)]) -> bool {
    let value = if modulus == 0 {
        digits.parse::<u32>().ok()
    } else {
        Some(digits_mod(digits, modulus))
    };
    value.is_some_and(|value| ranges.iter().any(|&(first, last)| (first..=last).contains(&value)))
}

fn relation(p: Operands<'_>, operand: Operand, modulus: u32, ranges: &[(u32, u32)]) -> bool {
    match operand {
        Operand::N => p.fraction_trimmed.is_empty()
            && digits_in_ranges(p.integer, modulus, ranges),
        Operand::I => digits_in_ranges(p.integer, modulus, ranges),
        Operand::F => digits_in_ranges(if p.fraction.is_empty() { "0" } else { p.fraction }, modulus, ranges),
        Operand::T => digits_in_ranges(if p.fraction_trimmed.is_empty() { "0" } else { p.fraction_trimmed }, modulus, ranges),
        Operand::V | Operand::W => {
            let mut value = if matches!(operand, Operand::V) { p.fraction.len() } else { p.fraction_trimmed.len() } as u32;
            if modulus != 0 { value %= modulus; }
            ranges.iter().any(|&(first, last)| (first..=last).contains(&value))
        }
        Operand::C | Operand::E => {
            let value = if modulus == 0 { p.compact_exponent } else { p.compact_exponent % modulus };
            ranges.iter().any(|&(first, last)| (first..=last).contains(&value))
        }
    }
}

pub(crate) fn select_cardinal(lang: &str, decimal: &str, compact_exponent: u32) -> &'static str {
    let p = Operands::new(decimal, compact_exponent);
    match lang {
        "en" => {
        if relation(p, Operand::I, 0, &[(1, 1)]) && relation(p, Operand::V, 0, &[(0, 0)]) { return "one"; }
        "other"
        }
        "de" => {
        if relation(p, Operand::I, 0, &[(1, 1)]) && relation(p, Operand::V, 0, &[(0, 0)]) { return "one"; }
        "other"
        }
        "fr" => {
        if relation(p, Operand::I, 0, &[(0, 0), (1, 1)]) { return "one"; }
        if (relation(p, Operand::E, 0, &[(0, 0)]) && !relation(p, Operand::I, 0, &[(0, 0)]) && relation(p, Operand::I, 1000000, &[(0, 0)]) && relation(p, Operand::V, 0, &[(0, 0)])) || (!relation(p, Operand::E, 0, &[(0, 5)])) { return "many"; }
        "other"
        }
        "es" => {
        if relation(p, Operand::N, 0, &[(1, 1)]) { return "one"; }
        if (relation(p, Operand::E, 0, &[(0, 0)]) && !relation(p, Operand::I, 0, &[(0, 0)]) && relation(p, Operand::I, 1000000, &[(0, 0)]) && relation(p, Operand::V, 0, &[(0, 0)])) || (!relation(p, Operand::E, 0, &[(0, 5)])) { return "many"; }
        "other"
        }
        "it" => {
        if relation(p, Operand::I, 0, &[(1, 1)]) && relation(p, Operand::V, 0, &[(0, 0)]) { return "one"; }
        if (relation(p, Operand::E, 0, &[(0, 0)]) && !relation(p, Operand::I, 0, &[(0, 0)]) && relation(p, Operand::I, 1000000, &[(0, 0)]) && relation(p, Operand::V, 0, &[(0, 0)])) || (!relation(p, Operand::E, 0, &[(0, 5)])) { return "many"; }
        "other"
        }
        "pt" => {
        if relation(p, Operand::I, 0, &[(0, 1)]) { return "one"; }
        if (relation(p, Operand::E, 0, &[(0, 0)]) && !relation(p, Operand::I, 0, &[(0, 0)]) && relation(p, Operand::I, 1000000, &[(0, 0)]) && relation(p, Operand::V, 0, &[(0, 0)])) || (!relation(p, Operand::E, 0, &[(0, 5)])) { return "many"; }
        "other"
        }
        "nl" => {
        if relation(p, Operand::I, 0, &[(1, 1)]) && relation(p, Operand::V, 0, &[(0, 0)]) { return "one"; }
        "other"
        }
        "ja" => {
        "other"
        }
        "zh" => {
        "other"
        }
        "ko" => {
        "other"
        }
        "ru" => {
        if relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 10, &[(1, 1)]) && !relation(p, Operand::I, 100, &[(11, 11)]) { return "one"; }
        if relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 10, &[(2, 4)]) && !relation(p, Operand::I, 100, &[(12, 14)]) { return "few"; }
        if (relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 10, &[(0, 0)])) || (relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 10, &[(5, 9)])) || (relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 100, &[(11, 14)])) { return "many"; }
        "other"
        }
        "ar" => {
        if relation(p, Operand::N, 0, &[(0, 0)]) { return "zero"; }
        if relation(p, Operand::N, 0, &[(1, 1)]) { return "one"; }
        if relation(p, Operand::N, 0, &[(2, 2)]) { return "two"; }
        if relation(p, Operand::N, 100, &[(3, 10)]) { return "few"; }
        if relation(p, Operand::N, 100, &[(11, 99)]) { return "many"; }
        "other"
        }
        "sr" => {
        if (relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 10, &[(1, 1)]) && !relation(p, Operand::I, 100, &[(11, 11)])) || (relation(p, Operand::F, 10, &[(1, 1)]) && !relation(p, Operand::F, 100, &[(11, 11)])) { return "one"; }
        if (relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 10, &[(2, 4)]) && !relation(p, Operand::I, 100, &[(12, 14)])) || (relation(p, Operand::F, 10, &[(2, 4)]) && !relation(p, Operand::F, 100, &[(12, 14)])) { return "few"; }
        "other"
        }
        "th" => {
        "other"
        }
        "gv" => {
        if relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 10, &[(1, 1)]) { return "one"; }
        if relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 10, &[(2, 2)]) { return "two"; }
        if relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 100, &[(0, 0), (20, 20), (40, 40), (60, 60), (80, 80)]) { return "few"; }
        if !relation(p, Operand::V, 0, &[(0, 0)]) { return "many"; }
        "other"
        }
        "sl" => {
        if relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 100, &[(1, 1)]) { return "one"; }
        if relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 100, &[(2, 2)]) { return "two"; }
        if (relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 100, &[(3, 4)])) || (!relation(p, Operand::V, 0, &[(0, 0)])) { return "few"; }
        "other"
        }
        "pl" => {
        if relation(p, Operand::I, 0, &[(1, 1)]) && relation(p, Operand::V, 0, &[(0, 0)]) { return "one"; }
        if relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 10, &[(2, 4)]) && !relation(p, Operand::I, 100, &[(12, 14)]) { return "few"; }
        if (relation(p, Operand::V, 0, &[(0, 0)]) && !relation(p, Operand::I, 0, &[(1, 1)]) && relation(p, Operand::I, 10, &[(0, 1)])) || (relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 10, &[(5, 9)])) || (relation(p, Operand::V, 0, &[(0, 0)]) && relation(p, Operand::I, 100, &[(12, 14)])) { return "many"; }
        "other"
        }
        "si" => {
        if (relation(p, Operand::N, 0, &[(0, 0), (1, 1)])) || (relation(p, Operand::I, 0, &[(0, 0)]) && relation(p, Operand::F, 0, &[(1, 1)])) { return "one"; }
        "other"
        }
        "ln" => {
        if relation(p, Operand::N, 0, &[(0, 1)]) { return "one"; }
        "other"
        }
        "sv" => {
        if relation(p, Operand::I, 0, &[(1, 1)]) && relation(p, Operand::V, 0, &[(0, 0)]) { return "one"; }
        "other"
        }
        "hi" => {
        if (relation(p, Operand::I, 0, &[(0, 0)])) || (relation(p, Operand::N, 0, &[(1, 1)])) { return "one"; }
        "other"
        }
        _ => "other",
    }
}

pub(crate) fn select_ordinal(lang: &str, decimal: &str, compact_exponent: u32) -> &'static str {
    let p = Operands::new(decimal, compact_exponent);
    match lang {
        "en" => {
        if relation(p, Operand::N, 10, &[(1, 1)]) && !relation(p, Operand::N, 100, &[(11, 11)]) { return "one"; }
        if relation(p, Operand::N, 10, &[(2, 2)]) && !relation(p, Operand::N, 100, &[(12, 12)]) { return "two"; }
        if relation(p, Operand::N, 10, &[(3, 3)]) && !relation(p, Operand::N, 100, &[(13, 13)]) { return "few"; }
        "other"
        }
        "de" => {
        "other"
        }
        "fr" => {
        if relation(p, Operand::N, 0, &[(1, 1)]) { return "one"; }
        "other"
        }
        "es" => {
        "other"
        }
        "it" => {
        if relation(p, Operand::N, 0, &[(11, 11), (8, 8), (80, 80), (800, 800)]) { return "many"; }
        "other"
        }
        "pt" => {
        "other"
        }
        "nl" => {
        "other"
        }
        "ja" => {
        "other"
        }
        "zh" => {
        "other"
        }
        "ko" => {
        "other"
        }
        "ru" => {
        "other"
        }
        "ar" => {
        "other"
        }
        "sr" => {
        "other"
        }
        "th" => {
        "other"
        }
        "gv" => {
        "other"
        }
        "sl" => {
        "other"
        }
        "pl" => {
        "other"
        }
        "si" => {
        "other"
        }
        "ln" => {
        "other"
        }
        "sv" => {
        if relation(p, Operand::N, 10, &[(1, 1), (2, 2)]) && !relation(p, Operand::N, 100, &[(11, 11), (12, 12)]) { return "one"; }
        "other"
        }
        "hi" => {
        if relation(p, Operand::N, 0, &[(1, 1)]) { return "one"; }
        if relation(p, Operand::N, 0, &[(2, 2), (3, 3)]) { return "two"; }
        if relation(p, Operand::N, 0, &[(4, 4)]) { return "few"; }
        if relation(p, Operand::N, 0, &[(6, 6)]) { return "many"; }
        "other"
        }
        _ => "other",
    }
}

pub(crate) fn categories(lang: &str, kind: &str) -> &'static [&'static str] {
    match (kind, lang) {
        ("cardinal", "en" | "de" | "nl" | "si" | "ln" | "sv" | "hi") => &["one", "other"],
        ("cardinal", "fr" | "es" | "it" | "pt") => &["one", "many", "other"],
        ("cardinal", "ja" | "zh" | "ko" | "th") => &["other"],
        ("cardinal", "ru" | "pl") => &["one", "few", "many", "other"],
        ("cardinal", "ar") => &["zero", "one", "two", "few", "many", "other"],
        ("cardinal", "sr") => &["one", "few", "other"],
        ("cardinal", "gv") => &["one", "two", "few", "many", "other"],
        ("cardinal", "sl") => &["one", "two", "few", "other"],
        ("ordinal", "en") => &["one", "two", "few", "other"],
        ("ordinal", "de" | "es" | "pt" | "nl" | "ja" | "zh" | "ko" | "ru" | "ar" | "sr" | "th" | "gv" | "sl" | "pl" | "si" | "ln") => &["other"],
        ("ordinal", "fr" | "sv") => &["one", "other"],
        ("ordinal", "it") => &["many", "other"],
        ("ordinal", "hi") => &["one", "two", "few", "many", "other"],
        _ => &["other"],
    }
}

pub(crate) fn select_range(lang: &str, start: &str, end: &str) -> &'static str {
    match (lang, start, end) {
        ("en", "one", "other") => "other",
        ("en", "other", "one") => "other",
        ("en", "other", "other") => "other",
        ("de", "one", "other") => "other",
        ("de", "other", "one") => "one",
        ("de", "other", "other") => "other",
        ("fr", "one", "one") => "one",
        ("fr", "one", "other") => "other",
        ("fr", "other", "other") => "other",
        ("es", "one", "other") => "other",
        ("es", "other", "one") => "other",
        ("es", "other", "other") => "other",
        ("it", "one", "other") => "other",
        ("it", "other", "one") => "one",
        ("it", "other", "other") => "other",
        ("pt", "one", "one") => "one",
        ("pt", "one", "other") => "other",
        ("pt", "other", "other") => "other",
        ("nl", "one", "other") => "other",
        ("nl", "other", "one") => "one",
        ("nl", "other", "other") => "other",
        ("ja", "other", "other") => "other",
        ("zh", "other", "other") => "other",
        ("ko", "other", "other") => "other",
        ("ru", "few", "few") => "few",
        ("ru", "few", "many") => "many",
        ("ru", "few", "one") => "one",
        ("ru", "few", "other") => "other",
        ("ru", "many", "few") => "few",
        ("ru", "many", "many") => "many",
        ("ru", "many", "one") => "one",
        ("ru", "many", "other") => "other",
        ("ru", "one", "few") => "few",
        ("ru", "one", "many") => "many",
        ("ru", "one", "one") => "one",
        ("ru", "one", "other") => "other",
        ("ru", "other", "few") => "few",
        ("ru", "other", "many") => "many",
        ("ru", "other", "one") => "one",
        ("ru", "other", "other") => "other",
        ("ar", "few", "few") => "few",
        ("ar", "few", "many") => "many",
        ("ar", "few", "other") => "other",
        ("ar", "many", "few") => "few",
        ("ar", "many", "many") => "many",
        ("ar", "many", "other") => "other",
        ("ar", "one", "few") => "few",
        ("ar", "one", "many") => "many",
        ("ar", "one", "other") => "other",
        ("ar", "one", "two") => "other",
        ("ar", "other", "few") => "few",
        ("ar", "other", "many") => "many",
        ("ar", "other", "one") => "other",
        ("ar", "other", "other") => "other",
        ("ar", "other", "two") => "other",
        ("ar", "two", "few") => "few",
        ("ar", "two", "many") => "many",
        ("ar", "two", "other") => "other",
        ("ar", "zero", "few") => "few",
        ("ar", "zero", "many") => "many",
        ("ar", "zero", "one") => "zero",
        ("ar", "zero", "other") => "other",
        ("ar", "zero", "two") => "zero",
        ("sr", "few", "few") => "few",
        ("sr", "few", "one") => "one",
        ("sr", "few", "other") => "other",
        ("sr", "one", "few") => "few",
        ("sr", "one", "one") => "one",
        ("sr", "one", "other") => "other",
        ("sr", "other", "few") => "few",
        ("sr", "other", "one") => "one",
        ("sr", "other", "other") => "other",
        ("th", "other", "other") => "other",
        ("sl", "few", "few") => "few",
        ("sl", "few", "one") => "few",
        ("sl", "few", "other") => "other",
        ("sl", "few", "two") => "two",
        ("sl", "one", "few") => "few",
        ("sl", "one", "one") => "few",
        ("sl", "one", "other") => "other",
        ("sl", "one", "two") => "two",
        ("sl", "other", "few") => "few",
        ("sl", "other", "one") => "few",
        ("sl", "other", "other") => "other",
        ("sl", "other", "two") => "two",
        ("sl", "two", "few") => "few",
        ("sl", "two", "one") => "few",
        ("sl", "two", "other") => "other",
        ("sl", "two", "two") => "two",
        ("pl", "few", "few") => "few",
        ("pl", "few", "many") => "many",
        ("pl", "few", "other") => "other",
        ("pl", "many", "few") => "few",
        ("pl", "many", "many") => "many",
        ("pl", "many", "one") => "one",
        ("pl", "many", "other") => "other",
        ("pl", "one", "few") => "few",
        ("pl", "one", "many") => "many",
        ("pl", "one", "other") => "other",
        ("pl", "other", "few") => "few",
        ("pl", "other", "many") => "many",
        ("pl", "other", "one") => "one",
        ("pl", "other", "other") => "other",
        ("si", "one", "one") => "one",
        ("si", "one", "other") => "other",
        ("si", "other", "one") => "other",
        ("si", "other", "other") => "other",
        ("sv", "one", "other") => "other",
        ("sv", "other", "one") => "other",
        ("sv", "other", "other") => "other",
        ("hi", "one", "one") => "one",
        ("hi", "one", "other") => "other",
        ("hi", "other", "other") => "other",
        _ => "other",
    }
}

#[cfg(test)]
const CARDINAL_SAMPLES: &[(&str, &str, u32, &str)] = &[
    ("en", "1", 0, "one"),
    ("en", "0", 0, "other"),
    ("en", "2", 0, "other"),
    ("en", "16", 0, "other"),
    ("en", "100", 0, "other"),
    ("en", "1000", 0, "other"),
    ("en", "10000", 0, "other"),
    ("en", "100000", 0, "other"),
    ("en", "1000000", 0, "other"),
    ("en", "0.0", 0, "other"),
    ("en", "1.5", 0, "other"),
    ("en", "10.0", 0, "other"),
    ("en", "100.0", 0, "other"),
    ("en", "1000.0", 0, "other"),
    ("en", "10000.0", 0, "other"),
    ("en", "100000.0", 0, "other"),
    ("en", "1000000.0", 0, "other"),
    ("de", "1", 0, "one"),
    ("de", "0", 0, "other"),
    ("de", "2", 0, "other"),
    ("de", "16", 0, "other"),
    ("de", "100", 0, "other"),
    ("de", "1000", 0, "other"),
    ("de", "10000", 0, "other"),
    ("de", "100000", 0, "other"),
    ("de", "1000000", 0, "other"),
    ("de", "0.0", 0, "other"),
    ("de", "1.5", 0, "other"),
    ("de", "10.0", 0, "other"),
    ("de", "100.0", 0, "other"),
    ("de", "1000.0", 0, "other"),
    ("de", "10000.0", 0, "other"),
    ("de", "100000.0", 0, "other"),
    ("de", "1000000.0", 0, "other"),
    ("fr", "0", 0, "one"),
    ("fr", "1", 0, "one"),
    ("fr", "0.0", 0, "one"),
    ("fr", "1.5", 0, "one"),
    ("fr", "1000000", 0, "many"),
    ("fr", "1000000", 6, "many"),
    ("fr", "2000000", 6, "many"),
    ("fr", "3000000", 6, "many"),
    ("fr", "4000000", 6, "many"),
    ("fr", "5000000", 6, "many"),
    ("fr", "6000000", 6, "many"),
    ("fr", "1000000.1", 6, "many"),
    ("fr", "1100000", 6, "many"),
    ("fr", "2000000.1", 6, "many"),
    ("fr", "2100000", 6, "many"),
    ("fr", "3000000.1", 6, "many"),
    ("fr", "3100000", 6, "many"),
    ("fr", "2", 0, "other"),
    ("fr", "17", 0, "other"),
    ("fr", "100", 0, "other"),
    ("fr", "1000", 0, "other"),
    ("fr", "10000", 0, "other"),
    ("fr", "100000", 0, "other"),
    ("fr", "1000", 3, "other"),
    ("fr", "2000", 3, "other"),
    ("fr", "3000", 3, "other"),
    ("fr", "4000", 3, "other"),
    ("fr", "5000", 3, "other"),
    ("fr", "6000", 3, "other"),
    ("fr", "2.0", 0, "other"),
    ("fr", "3.5", 0, "other"),
    ("fr", "10.0", 0, "other"),
    ("fr", "100.0", 0, "other"),
    ("fr", "1000.0", 0, "other"),
    ("fr", "10000.0", 0, "other"),
    ("fr", "100000.0", 0, "other"),
    ("fr", "1000000.0", 0, "other"),
    ("fr", "1000.1", 3, "other"),
    ("fr", "1100", 3, "other"),
    ("fr", "2000.1", 3, "other"),
    ("fr", "2100", 3, "other"),
    ("fr", "3000.1", 3, "other"),
    ("fr", "3100", 3, "other"),
    ("es", "1", 0, "one"),
    ("es", "1.0", 0, "one"),
    ("es", "1.00", 0, "one"),
    ("es", "1.000", 0, "one"),
    ("es", "1.0000", 0, "one"),
    ("es", "1000000", 0, "many"),
    ("es", "1000000", 6, "many"),
    ("es", "2000000", 6, "many"),
    ("es", "3000000", 6, "many"),
    ("es", "4000000", 6, "many"),
    ("es", "5000000", 6, "many"),
    ("es", "6000000", 6, "many"),
    ("es", "1000000.1", 6, "many"),
    ("es", "1100000", 6, "many"),
    ("es", "2000000.1", 6, "many"),
    ("es", "2100000", 6, "many"),
    ("es", "3000000.1", 6, "many"),
    ("es", "3100000", 6, "many"),
    ("es", "0", 0, "other"),
    ("es", "2", 0, "other"),
    ("es", "16", 0, "other"),
    ("es", "100", 0, "other"),
    ("es", "1000", 0, "other"),
    ("es", "10000", 0, "other"),
    ("es", "100000", 0, "other"),
    ("es", "1000", 3, "other"),
    ("es", "2000", 3, "other"),
    ("es", "3000", 3, "other"),
    ("es", "4000", 3, "other"),
    ("es", "5000", 3, "other"),
    ("es", "6000", 3, "other"),
    ("es", "0.0", 0, "other"),
    ("es", "0.9", 0, "other"),
    ("es", "1.1", 0, "other"),
    ("es", "1.6", 0, "other"),
    ("es", "10.0", 0, "other"),
    ("es", "100.0", 0, "other"),
    ("es", "1000.0", 0, "other"),
    ("es", "10000.0", 0, "other"),
    ("es", "100000.0", 0, "other"),
    ("es", "1000000.0", 0, "other"),
    ("es", "1000.1", 3, "other"),
    ("es", "1100", 3, "other"),
    ("es", "2000.1", 3, "other"),
    ("es", "2100", 3, "other"),
    ("es", "3000.1", 3, "other"),
    ("es", "3100", 3, "other"),
    ("it", "1", 0, "one"),
    ("it", "1000000", 0, "many"),
    ("it", "1000000", 6, "many"),
    ("it", "2000000", 6, "many"),
    ("it", "3000000", 6, "many"),
    ("it", "4000000", 6, "many"),
    ("it", "5000000", 6, "many"),
    ("it", "6000000", 6, "many"),
    ("it", "1000000.1", 6, "many"),
    ("it", "1100000", 6, "many"),
    ("it", "2000000.1", 6, "many"),
    ("it", "2100000", 6, "many"),
    ("it", "3000000.1", 6, "many"),
    ("it", "3100000", 6, "many"),
    ("it", "0", 0, "other"),
    ("it", "2", 0, "other"),
    ("it", "16", 0, "other"),
    ("it", "100", 0, "other"),
    ("it", "1000", 0, "other"),
    ("it", "10000", 0, "other"),
    ("it", "100000", 0, "other"),
    ("it", "1000", 3, "other"),
    ("it", "2000", 3, "other"),
    ("it", "3000", 3, "other"),
    ("it", "4000", 3, "other"),
    ("it", "5000", 3, "other"),
    ("it", "6000", 3, "other"),
    ("it", "0.0", 0, "other"),
    ("it", "1.5", 0, "other"),
    ("it", "10.0", 0, "other"),
    ("it", "100.0", 0, "other"),
    ("it", "1000.0", 0, "other"),
    ("it", "10000.0", 0, "other"),
    ("it", "100000.0", 0, "other"),
    ("it", "1000000.0", 0, "other"),
    ("it", "1000.1", 3, "other"),
    ("it", "1100", 3, "other"),
    ("it", "2000.1", 3, "other"),
    ("it", "2100", 3, "other"),
    ("it", "3000.1", 3, "other"),
    ("it", "3100", 3, "other"),
    ("pt", "0", 0, "one"),
    ("pt", "1", 0, "one"),
    ("pt", "0.0", 0, "one"),
    ("pt", "1.5", 0, "one"),
    ("pt", "1000000", 0, "many"),
    ("pt", "1000000", 6, "many"),
    ("pt", "2000000", 6, "many"),
    ("pt", "3000000", 6, "many"),
    ("pt", "4000000", 6, "many"),
    ("pt", "5000000", 6, "many"),
    ("pt", "6000000", 6, "many"),
    ("pt", "1000000.1", 6, "many"),
    ("pt", "1100000", 6, "many"),
    ("pt", "2000000.1", 6, "many"),
    ("pt", "2100000", 6, "many"),
    ("pt", "3000000.1", 6, "many"),
    ("pt", "3100000", 6, "many"),
    ("pt", "2", 0, "other"),
    ("pt", "17", 0, "other"),
    ("pt", "100", 0, "other"),
    ("pt", "1000", 0, "other"),
    ("pt", "10000", 0, "other"),
    ("pt", "100000", 0, "other"),
    ("pt", "1000", 3, "other"),
    ("pt", "2000", 3, "other"),
    ("pt", "3000", 3, "other"),
    ("pt", "4000", 3, "other"),
    ("pt", "5000", 3, "other"),
    ("pt", "6000", 3, "other"),
    ("pt", "2.0", 0, "other"),
    ("pt", "3.5", 0, "other"),
    ("pt", "10.0", 0, "other"),
    ("pt", "100.0", 0, "other"),
    ("pt", "1000.0", 0, "other"),
    ("pt", "10000.0", 0, "other"),
    ("pt", "100000.0", 0, "other"),
    ("pt", "1000000.0", 0, "other"),
    ("pt", "1000.1", 3, "other"),
    ("pt", "1100", 3, "other"),
    ("pt", "2000.1", 3, "other"),
    ("pt", "2100", 3, "other"),
    ("pt", "3000.1", 3, "other"),
    ("pt", "3100", 3, "other"),
    ("nl", "1", 0, "one"),
    ("nl", "0", 0, "other"),
    ("nl", "2", 0, "other"),
    ("nl", "16", 0, "other"),
    ("nl", "100", 0, "other"),
    ("nl", "1000", 0, "other"),
    ("nl", "10000", 0, "other"),
    ("nl", "100000", 0, "other"),
    ("nl", "1000000", 0, "other"),
    ("nl", "0.0", 0, "other"),
    ("nl", "1.5", 0, "other"),
    ("nl", "10.0", 0, "other"),
    ("nl", "100.0", 0, "other"),
    ("nl", "1000.0", 0, "other"),
    ("nl", "10000.0", 0, "other"),
    ("nl", "100000.0", 0, "other"),
    ("nl", "1000000.0", 0, "other"),
    ("ja", "0", 0, "other"),
    ("ja", "15", 0, "other"),
    ("ja", "100", 0, "other"),
    ("ja", "1000", 0, "other"),
    ("ja", "10000", 0, "other"),
    ("ja", "100000", 0, "other"),
    ("ja", "1000000", 0, "other"),
    ("ja", "0.0", 0, "other"),
    ("ja", "1.5", 0, "other"),
    ("ja", "10.0", 0, "other"),
    ("ja", "100.0", 0, "other"),
    ("ja", "1000.0", 0, "other"),
    ("ja", "10000.0", 0, "other"),
    ("ja", "100000.0", 0, "other"),
    ("ja", "1000000.0", 0, "other"),
    ("zh", "0", 0, "other"),
    ("zh", "15", 0, "other"),
    ("zh", "100", 0, "other"),
    ("zh", "1000", 0, "other"),
    ("zh", "10000", 0, "other"),
    ("zh", "100000", 0, "other"),
    ("zh", "1000000", 0, "other"),
    ("zh", "0.0", 0, "other"),
    ("zh", "1.5", 0, "other"),
    ("zh", "10.0", 0, "other"),
    ("zh", "100.0", 0, "other"),
    ("zh", "1000.0", 0, "other"),
    ("zh", "10000.0", 0, "other"),
    ("zh", "100000.0", 0, "other"),
    ("zh", "1000000.0", 0, "other"),
    ("ko", "0", 0, "other"),
    ("ko", "15", 0, "other"),
    ("ko", "100", 0, "other"),
    ("ko", "1000", 0, "other"),
    ("ko", "10000", 0, "other"),
    ("ko", "100000", 0, "other"),
    ("ko", "1000000", 0, "other"),
    ("ko", "0.0", 0, "other"),
    ("ko", "1.5", 0, "other"),
    ("ko", "10.0", 0, "other"),
    ("ko", "100.0", 0, "other"),
    ("ko", "1000.0", 0, "other"),
    ("ko", "10000.0", 0, "other"),
    ("ko", "100000.0", 0, "other"),
    ("ko", "1000000.0", 0, "other"),
    ("ru", "1", 0, "one"),
    ("ru", "21", 0, "one"),
    ("ru", "31", 0, "one"),
    ("ru", "41", 0, "one"),
    ("ru", "51", 0, "one"),
    ("ru", "61", 0, "one"),
    ("ru", "71", 0, "one"),
    ("ru", "81", 0, "one"),
    ("ru", "101", 0, "one"),
    ("ru", "1001", 0, "one"),
    ("ru", "2", 0, "few"),
    ("ru", "4", 0, "few"),
    ("ru", "22", 0, "few"),
    ("ru", "24", 0, "few"),
    ("ru", "32", 0, "few"),
    ("ru", "34", 0, "few"),
    ("ru", "42", 0, "few"),
    ("ru", "44", 0, "few"),
    ("ru", "52", 0, "few"),
    ("ru", "54", 0, "few"),
    ("ru", "62", 0, "few"),
    ("ru", "102", 0, "few"),
    ("ru", "1002", 0, "few"),
    ("ru", "0", 0, "many"),
    ("ru", "5", 0, "many"),
    ("ru", "19", 0, "many"),
    ("ru", "100", 0, "many"),
    ("ru", "1000", 0, "many"),
    ("ru", "10000", 0, "many"),
    ("ru", "100000", 0, "many"),
    ("ru", "1000000", 0, "many"),
    ("ru", "0.0", 0, "other"),
    ("ru", "1.5", 0, "other"),
    ("ru", "10.0", 0, "other"),
    ("ru", "100.0", 0, "other"),
    ("ru", "1000.0", 0, "other"),
    ("ru", "10000.0", 0, "other"),
    ("ru", "100000.0", 0, "other"),
    ("ru", "1000000.0", 0, "other"),
    ("ar", "0", 0, "zero"),
    ("ar", "0.0", 0, "zero"),
    ("ar", "0.00", 0, "zero"),
    ("ar", "0.000", 0, "zero"),
    ("ar", "0.0000", 0, "zero"),
    ("ar", "1", 0, "one"),
    ("ar", "1.0", 0, "one"),
    ("ar", "1.00", 0, "one"),
    ("ar", "1.000", 0, "one"),
    ("ar", "1.0000", 0, "one"),
    ("ar", "2", 0, "two"),
    ("ar", "2.0", 0, "two"),
    ("ar", "2.00", 0, "two"),
    ("ar", "2.000", 0, "two"),
    ("ar", "2.0000", 0, "two"),
    ("ar", "3", 0, "few"),
    ("ar", "10", 0, "few"),
    ("ar", "103", 0, "few"),
    ("ar", "110", 0, "few"),
    ("ar", "1003", 0, "few"),
    ("ar", "3.0", 0, "few"),
    ("ar", "4.0", 0, "few"),
    ("ar", "5.0", 0, "few"),
    ("ar", "6.0", 0, "few"),
    ("ar", "7.0", 0, "few"),
    ("ar", "8.0", 0, "few"),
    ("ar", "9.0", 0, "few"),
    ("ar", "10.0", 0, "few"),
    ("ar", "103.0", 0, "few"),
    ("ar", "1003.0", 0, "few"),
    ("ar", "11", 0, "many"),
    ("ar", "26", 0, "many"),
    ("ar", "111", 0, "many"),
    ("ar", "1011", 0, "many"),
    ("ar", "11.0", 0, "many"),
    ("ar", "12.0", 0, "many"),
    ("ar", "13.0", 0, "many"),
    ("ar", "14.0", 0, "many"),
    ("ar", "15.0", 0, "many"),
    ("ar", "16.0", 0, "many"),
    ("ar", "17.0", 0, "many"),
    ("ar", "18.0", 0, "many"),
    ("ar", "111.0", 0, "many"),
    ("ar", "1011.0", 0, "many"),
    ("ar", "100", 0, "other"),
    ("ar", "102", 0, "other"),
    ("ar", "200", 0, "other"),
    ("ar", "202", 0, "other"),
    ("ar", "300", 0, "other"),
    ("ar", "302", 0, "other"),
    ("ar", "400", 0, "other"),
    ("ar", "402", 0, "other"),
    ("ar", "500", 0, "other"),
    ("ar", "502", 0, "other"),
    ("ar", "600", 0, "other"),
    ("ar", "1000", 0, "other"),
    ("ar", "10000", 0, "other"),
    ("ar", "100000", 0, "other"),
    ("ar", "1000000", 0, "other"),
    ("ar", "0.1", 0, "other"),
    ("ar", "0.9", 0, "other"),
    ("ar", "1.1", 0, "other"),
    ("ar", "1.7", 0, "other"),
    ("ar", "10.1", 0, "other"),
    ("ar", "100.0", 0, "other"),
    ("ar", "1000.0", 0, "other"),
    ("ar", "10000.0", 0, "other"),
    ("ar", "100000.0", 0, "other"),
    ("ar", "1000000.0", 0, "other"),
    ("sr", "1", 0, "one"),
    ("sr", "21", 0, "one"),
    ("sr", "31", 0, "one"),
    ("sr", "41", 0, "one"),
    ("sr", "51", 0, "one"),
    ("sr", "61", 0, "one"),
    ("sr", "71", 0, "one"),
    ("sr", "81", 0, "one"),
    ("sr", "101", 0, "one"),
    ("sr", "1001", 0, "one"),
    ("sr", "0.1", 0, "one"),
    ("sr", "1.1", 0, "one"),
    ("sr", "2.1", 0, "one"),
    ("sr", "3.1", 0, "one"),
    ("sr", "4.1", 0, "one"),
    ("sr", "5.1", 0, "one"),
    ("sr", "6.1", 0, "one"),
    ("sr", "7.1", 0, "one"),
    ("sr", "10.1", 0, "one"),
    ("sr", "100.1", 0, "one"),
    ("sr", "1000.1", 0, "one"),
    ("sr", "2", 0, "few"),
    ("sr", "4", 0, "few"),
    ("sr", "22", 0, "few"),
    ("sr", "24", 0, "few"),
    ("sr", "32", 0, "few"),
    ("sr", "34", 0, "few"),
    ("sr", "42", 0, "few"),
    ("sr", "44", 0, "few"),
    ("sr", "52", 0, "few"),
    ("sr", "54", 0, "few"),
    ("sr", "62", 0, "few"),
    ("sr", "102", 0, "few"),
    ("sr", "1002", 0, "few"),
    ("sr", "0.2", 0, "few"),
    ("sr", "0.4", 0, "few"),
    ("sr", "1.2", 0, "few"),
    ("sr", "1.4", 0, "few"),
    ("sr", "2.2", 0, "few"),
    ("sr", "2.4", 0, "few"),
    ("sr", "3.2", 0, "few"),
    ("sr", "3.4", 0, "few"),
    ("sr", "4.2", 0, "few"),
    ("sr", "4.4", 0, "few"),
    ("sr", "5.2", 0, "few"),
    ("sr", "10.2", 0, "few"),
    ("sr", "100.2", 0, "few"),
    ("sr", "1000.2", 0, "few"),
    ("sr", "0", 0, "other"),
    ("sr", "5", 0, "other"),
    ("sr", "19", 0, "other"),
    ("sr", "100", 0, "other"),
    ("sr", "1000", 0, "other"),
    ("sr", "10000", 0, "other"),
    ("sr", "100000", 0, "other"),
    ("sr", "1000000", 0, "other"),
    ("sr", "0.0", 0, "other"),
    ("sr", "0.5", 0, "other"),
    ("sr", "1.0", 0, "other"),
    ("sr", "1.5", 0, "other"),
    ("sr", "2.0", 0, "other"),
    ("sr", "2.5", 0, "other"),
    ("sr", "2.7", 0, "other"),
    ("sr", "10.0", 0, "other"),
    ("sr", "100.0", 0, "other"),
    ("sr", "1000.0", 0, "other"),
    ("sr", "10000.0", 0, "other"),
    ("sr", "100000.0", 0, "other"),
    ("sr", "1000000.0", 0, "other"),
    ("th", "0", 0, "other"),
    ("th", "15", 0, "other"),
    ("th", "100", 0, "other"),
    ("th", "1000", 0, "other"),
    ("th", "10000", 0, "other"),
    ("th", "100000", 0, "other"),
    ("th", "1000000", 0, "other"),
    ("th", "0.0", 0, "other"),
    ("th", "1.5", 0, "other"),
    ("th", "10.0", 0, "other"),
    ("th", "100.0", 0, "other"),
    ("th", "1000.0", 0, "other"),
    ("th", "10000.0", 0, "other"),
    ("th", "100000.0", 0, "other"),
    ("th", "1000000.0", 0, "other"),
    ("gv", "1", 0, "one"),
    ("gv", "11", 0, "one"),
    ("gv", "21", 0, "one"),
    ("gv", "31", 0, "one"),
    ("gv", "41", 0, "one"),
    ("gv", "51", 0, "one"),
    ("gv", "61", 0, "one"),
    ("gv", "71", 0, "one"),
    ("gv", "101", 0, "one"),
    ("gv", "1001", 0, "one"),
    ("gv", "2", 0, "two"),
    ("gv", "12", 0, "two"),
    ("gv", "22", 0, "two"),
    ("gv", "32", 0, "two"),
    ("gv", "42", 0, "two"),
    ("gv", "52", 0, "two"),
    ("gv", "62", 0, "two"),
    ("gv", "72", 0, "two"),
    ("gv", "102", 0, "two"),
    ("gv", "1002", 0, "two"),
    ("gv", "0", 0, "few"),
    ("gv", "20", 0, "few"),
    ("gv", "40", 0, "few"),
    ("gv", "60", 0, "few"),
    ("gv", "80", 0, "few"),
    ("gv", "100", 0, "few"),
    ("gv", "120", 0, "few"),
    ("gv", "140", 0, "few"),
    ("gv", "1000", 0, "few"),
    ("gv", "10000", 0, "few"),
    ("gv", "100000", 0, "few"),
    ("gv", "1000000", 0, "few"),
    ("gv", "0.0", 0, "many"),
    ("gv", "1.5", 0, "many"),
    ("gv", "10.0", 0, "many"),
    ("gv", "100.0", 0, "many"),
    ("gv", "1000.0", 0, "many"),
    ("gv", "10000.0", 0, "many"),
    ("gv", "100000.0", 0, "many"),
    ("gv", "1000000.0", 0, "many"),
    ("gv", "3", 0, "other"),
    ("gv", "10", 0, "other"),
    ("gv", "13", 0, "other"),
    ("gv", "19", 0, "other"),
    ("gv", "23", 0, "other"),
    ("gv", "103", 0, "other"),
    ("gv", "1003", 0, "other"),
    ("sl", "1", 0, "one"),
    ("sl", "101", 0, "one"),
    ("sl", "201", 0, "one"),
    ("sl", "301", 0, "one"),
    ("sl", "401", 0, "one"),
    ("sl", "501", 0, "one"),
    ("sl", "601", 0, "one"),
    ("sl", "701", 0, "one"),
    ("sl", "1001", 0, "one"),
    ("sl", "2", 0, "two"),
    ("sl", "102", 0, "two"),
    ("sl", "202", 0, "two"),
    ("sl", "302", 0, "two"),
    ("sl", "402", 0, "two"),
    ("sl", "502", 0, "two"),
    ("sl", "602", 0, "two"),
    ("sl", "702", 0, "two"),
    ("sl", "1002", 0, "two"),
    ("sl", "3", 0, "few"),
    ("sl", "4", 0, "few"),
    ("sl", "103", 0, "few"),
    ("sl", "104", 0, "few"),
    ("sl", "203", 0, "few"),
    ("sl", "204", 0, "few"),
    ("sl", "303", 0, "few"),
    ("sl", "304", 0, "few"),
    ("sl", "403", 0, "few"),
    ("sl", "404", 0, "few"),
    ("sl", "503", 0, "few"),
    ("sl", "504", 0, "few"),
    ("sl", "603", 0, "few"),
    ("sl", "604", 0, "few"),
    ("sl", "703", 0, "few"),
    ("sl", "704", 0, "few"),
    ("sl", "1003", 0, "few"),
    ("sl", "0.0", 0, "few"),
    ("sl", "1.5", 0, "few"),
    ("sl", "10.0", 0, "few"),
    ("sl", "100.0", 0, "few"),
    ("sl", "1000.0", 0, "few"),
    ("sl", "10000.0", 0, "few"),
    ("sl", "100000.0", 0, "few"),
    ("sl", "1000000.0", 0, "few"),
    ("sl", "0", 0, "other"),
    ("sl", "5", 0, "other"),
    ("sl", "19", 0, "other"),
    ("sl", "100", 0, "other"),
    ("sl", "1000", 0, "other"),
    ("sl", "10000", 0, "other"),
    ("sl", "100000", 0, "other"),
    ("sl", "1000000", 0, "other"),
    ("pl", "1", 0, "one"),
    ("pl", "2", 0, "few"),
    ("pl", "4", 0, "few"),
    ("pl", "22", 0, "few"),
    ("pl", "24", 0, "few"),
    ("pl", "32", 0, "few"),
    ("pl", "34", 0, "few"),
    ("pl", "42", 0, "few"),
    ("pl", "44", 0, "few"),
    ("pl", "52", 0, "few"),
    ("pl", "54", 0, "few"),
    ("pl", "62", 0, "few"),
    ("pl", "102", 0, "few"),
    ("pl", "1002", 0, "few"),
    ("pl", "0", 0, "many"),
    ("pl", "5", 0, "many"),
    ("pl", "19", 0, "many"),
    ("pl", "100", 0, "many"),
    ("pl", "1000", 0, "many"),
    ("pl", "10000", 0, "many"),
    ("pl", "100000", 0, "many"),
    ("pl", "1000000", 0, "many"),
    ("pl", "0.0", 0, "other"),
    ("pl", "1.5", 0, "other"),
    ("pl", "10.0", 0, "other"),
    ("pl", "100.0", 0, "other"),
    ("pl", "1000.0", 0, "other"),
    ("pl", "10000.0", 0, "other"),
    ("pl", "100000.0", 0, "other"),
    ("pl", "1000000.0", 0, "other"),
    ("si", "0", 0, "one"),
    ("si", "1", 0, "one"),
    ("si", "0.0", 0, "one"),
    ("si", "0.1", 0, "one"),
    ("si", "1.0", 0, "one"),
    ("si", "0.00", 0, "one"),
    ("si", "0.01", 0, "one"),
    ("si", "1.00", 0, "one"),
    ("si", "0.000", 0, "one"),
    ("si", "0.001", 0, "one"),
    ("si", "1.000", 0, "one"),
    ("si", "0.0000", 0, "one"),
    ("si", "0.0001", 0, "one"),
    ("si", "1.0000", 0, "one"),
    ("si", "2", 0, "other"),
    ("si", "17", 0, "other"),
    ("si", "100", 0, "other"),
    ("si", "1000", 0, "other"),
    ("si", "10000", 0, "other"),
    ("si", "100000", 0, "other"),
    ("si", "1000000", 0, "other"),
    ("si", "0.2", 0, "other"),
    ("si", "0.9", 0, "other"),
    ("si", "1.1", 0, "other"),
    ("si", "1.8", 0, "other"),
    ("si", "10.0", 0, "other"),
    ("si", "100.0", 0, "other"),
    ("si", "1000.0", 0, "other"),
    ("si", "10000.0", 0, "other"),
    ("si", "100000.0", 0, "other"),
    ("si", "1000000.0", 0, "other"),
    ("ln", "0", 0, "one"),
    ("ln", "1", 0, "one"),
    ("ln", "0.0", 0, "one"),
    ("ln", "1.0", 0, "one"),
    ("ln", "0.00", 0, "one"),
    ("ln", "1.00", 0, "one"),
    ("ln", "0.000", 0, "one"),
    ("ln", "1.000", 0, "one"),
    ("ln", "0.0000", 0, "one"),
    ("ln", "1.0000", 0, "one"),
    ("ln", "2", 0, "other"),
    ("ln", "17", 0, "other"),
    ("ln", "100", 0, "other"),
    ("ln", "1000", 0, "other"),
    ("ln", "10000", 0, "other"),
    ("ln", "100000", 0, "other"),
    ("ln", "1000000", 0, "other"),
    ("ln", "0.1", 0, "other"),
    ("ln", "0.9", 0, "other"),
    ("ln", "1.1", 0, "other"),
    ("ln", "1.7", 0, "other"),
    ("ln", "10.0", 0, "other"),
    ("ln", "100.0", 0, "other"),
    ("ln", "1000.0", 0, "other"),
    ("ln", "10000.0", 0, "other"),
    ("ln", "100000.0", 0, "other"),
    ("ln", "1000000.0", 0, "other"),
    ("sv", "1", 0, "one"),
    ("sv", "0", 0, "other"),
    ("sv", "2", 0, "other"),
    ("sv", "16", 0, "other"),
    ("sv", "100", 0, "other"),
    ("sv", "1000", 0, "other"),
    ("sv", "10000", 0, "other"),
    ("sv", "100000", 0, "other"),
    ("sv", "1000000", 0, "other"),
    ("sv", "0.0", 0, "other"),
    ("sv", "1.5", 0, "other"),
    ("sv", "10.0", 0, "other"),
    ("sv", "100.0", 0, "other"),
    ("sv", "1000.0", 0, "other"),
    ("sv", "10000.0", 0, "other"),
    ("sv", "100000.0", 0, "other"),
    ("sv", "1000000.0", 0, "other"),
    ("hi", "0", 0, "one"),
    ("hi", "1", 0, "one"),
    ("hi", "0.0", 0, "one"),
    ("hi", "1.0", 0, "one"),
    ("hi", "0.00", 0, "one"),
    ("hi", "0.04", 0, "one"),
    ("hi", "2", 0, "other"),
    ("hi", "17", 0, "other"),
    ("hi", "100", 0, "other"),
    ("hi", "1000", 0, "other"),
    ("hi", "10000", 0, "other"),
    ("hi", "100000", 0, "other"),
    ("hi", "1000000", 0, "other"),
    ("hi", "1.1", 0, "other"),
    ("hi", "2.6", 0, "other"),
    ("hi", "10.0", 0, "other"),
    ("hi", "100.0", 0, "other"),
    ("hi", "1000.0", 0, "other"),
    ("hi", "10000.0", 0, "other"),
    ("hi", "100000.0", 0, "other"),
    ("hi", "1000000.0", 0, "other"),
];

#[cfg(test)]
const ORDINAL_SAMPLES: &[(&str, &str, u32, &str)] = &[
    ("en", "1", 0, "one"),
    ("en", "21", 0, "one"),
    ("en", "31", 0, "one"),
    ("en", "41", 0, "one"),
    ("en", "51", 0, "one"),
    ("en", "61", 0, "one"),
    ("en", "71", 0, "one"),
    ("en", "81", 0, "one"),
    ("en", "101", 0, "one"),
    ("en", "1001", 0, "one"),
    ("en", "2", 0, "two"),
    ("en", "22", 0, "two"),
    ("en", "32", 0, "two"),
    ("en", "42", 0, "two"),
    ("en", "52", 0, "two"),
    ("en", "62", 0, "two"),
    ("en", "72", 0, "two"),
    ("en", "82", 0, "two"),
    ("en", "102", 0, "two"),
    ("en", "1002", 0, "two"),
    ("en", "3", 0, "few"),
    ("en", "23", 0, "few"),
    ("en", "33", 0, "few"),
    ("en", "43", 0, "few"),
    ("en", "53", 0, "few"),
    ("en", "63", 0, "few"),
    ("en", "73", 0, "few"),
    ("en", "83", 0, "few"),
    ("en", "103", 0, "few"),
    ("en", "1003", 0, "few"),
    ("en", "0", 0, "other"),
    ("en", "4", 0, "other"),
    ("en", "18", 0, "other"),
    ("en", "100", 0, "other"),
    ("en", "1000", 0, "other"),
    ("en", "10000", 0, "other"),
    ("en", "100000", 0, "other"),
    ("en", "1000000", 0, "other"),
    ("de", "0", 0, "other"),
    ("de", "15", 0, "other"),
    ("de", "100", 0, "other"),
    ("de", "1000", 0, "other"),
    ("de", "10000", 0, "other"),
    ("de", "100000", 0, "other"),
    ("de", "1000000", 0, "other"),
    ("fr", "1", 0, "one"),
    ("fr", "0", 0, "other"),
    ("fr", "2", 0, "other"),
    ("fr", "16", 0, "other"),
    ("fr", "100", 0, "other"),
    ("fr", "1000", 0, "other"),
    ("fr", "10000", 0, "other"),
    ("fr", "100000", 0, "other"),
    ("fr", "1000000", 0, "other"),
    ("es", "0", 0, "other"),
    ("es", "15", 0, "other"),
    ("es", "100", 0, "other"),
    ("es", "1000", 0, "other"),
    ("es", "10000", 0, "other"),
    ("es", "100000", 0, "other"),
    ("es", "1000000", 0, "other"),
    ("it", "8", 0, "many"),
    ("it", "11", 0, "many"),
    ("it", "80", 0, "many"),
    ("it", "800", 0, "many"),
    ("it", "0", 0, "other"),
    ("it", "7", 0, "other"),
    ("it", "9", 0, "other"),
    ("it", "10", 0, "other"),
    ("it", "12", 0, "other"),
    ("it", "17", 0, "other"),
    ("it", "100", 0, "other"),
    ("it", "1000", 0, "other"),
    ("it", "10000", 0, "other"),
    ("it", "100000", 0, "other"),
    ("it", "1000000", 0, "other"),
    ("pt", "0", 0, "other"),
    ("pt", "15", 0, "other"),
    ("pt", "100", 0, "other"),
    ("pt", "1000", 0, "other"),
    ("pt", "10000", 0, "other"),
    ("pt", "100000", 0, "other"),
    ("pt", "1000000", 0, "other"),
    ("nl", "0", 0, "other"),
    ("nl", "15", 0, "other"),
    ("nl", "100", 0, "other"),
    ("nl", "1000", 0, "other"),
    ("nl", "10000", 0, "other"),
    ("nl", "100000", 0, "other"),
    ("nl", "1000000", 0, "other"),
    ("ja", "0", 0, "other"),
    ("ja", "15", 0, "other"),
    ("ja", "100", 0, "other"),
    ("ja", "1000", 0, "other"),
    ("ja", "10000", 0, "other"),
    ("ja", "100000", 0, "other"),
    ("ja", "1000000", 0, "other"),
    ("zh", "0", 0, "other"),
    ("zh", "15", 0, "other"),
    ("zh", "100", 0, "other"),
    ("zh", "1000", 0, "other"),
    ("zh", "10000", 0, "other"),
    ("zh", "100000", 0, "other"),
    ("zh", "1000000", 0, "other"),
    ("ko", "0", 0, "other"),
    ("ko", "15", 0, "other"),
    ("ko", "100", 0, "other"),
    ("ko", "1000", 0, "other"),
    ("ko", "10000", 0, "other"),
    ("ko", "100000", 0, "other"),
    ("ko", "1000000", 0, "other"),
    ("ru", "0", 0, "other"),
    ("ru", "15", 0, "other"),
    ("ru", "100", 0, "other"),
    ("ru", "1000", 0, "other"),
    ("ru", "10000", 0, "other"),
    ("ru", "100000", 0, "other"),
    ("ru", "1000000", 0, "other"),
    ("ar", "0", 0, "other"),
    ("ar", "15", 0, "other"),
    ("ar", "100", 0, "other"),
    ("ar", "1000", 0, "other"),
    ("ar", "10000", 0, "other"),
    ("ar", "100000", 0, "other"),
    ("ar", "1000000", 0, "other"),
    ("sr", "0", 0, "other"),
    ("sr", "15", 0, "other"),
    ("sr", "100", 0, "other"),
    ("sr", "1000", 0, "other"),
    ("sr", "10000", 0, "other"),
    ("sr", "100000", 0, "other"),
    ("sr", "1000000", 0, "other"),
    ("th", "0", 0, "other"),
    ("th", "15", 0, "other"),
    ("th", "100", 0, "other"),
    ("th", "1000", 0, "other"),
    ("th", "10000", 0, "other"),
    ("th", "100000", 0, "other"),
    ("th", "1000000", 0, "other"),
    ("sl", "0", 0, "other"),
    ("sl", "15", 0, "other"),
    ("sl", "100", 0, "other"),
    ("sl", "1000", 0, "other"),
    ("sl", "10000", 0, "other"),
    ("sl", "100000", 0, "other"),
    ("sl", "1000000", 0, "other"),
    ("pl", "0", 0, "other"),
    ("pl", "15", 0, "other"),
    ("pl", "100", 0, "other"),
    ("pl", "1000", 0, "other"),
    ("pl", "10000", 0, "other"),
    ("pl", "100000", 0, "other"),
    ("pl", "1000000", 0, "other"),
    ("si", "0", 0, "other"),
    ("si", "15", 0, "other"),
    ("si", "100", 0, "other"),
    ("si", "1000", 0, "other"),
    ("si", "10000", 0, "other"),
    ("si", "100000", 0, "other"),
    ("si", "1000000", 0, "other"),
    ("sv", "1", 0, "one"),
    ("sv", "2", 0, "one"),
    ("sv", "21", 0, "one"),
    ("sv", "22", 0, "one"),
    ("sv", "31", 0, "one"),
    ("sv", "32", 0, "one"),
    ("sv", "41", 0, "one"),
    ("sv", "42", 0, "one"),
    ("sv", "51", 0, "one"),
    ("sv", "52", 0, "one"),
    ("sv", "61", 0, "one"),
    ("sv", "62", 0, "one"),
    ("sv", "71", 0, "one"),
    ("sv", "72", 0, "one"),
    ("sv", "81", 0, "one"),
    ("sv", "82", 0, "one"),
    ("sv", "101", 0, "one"),
    ("sv", "1001", 0, "one"),
    ("sv", "0", 0, "other"),
    ("sv", "3", 0, "other"),
    ("sv", "17", 0, "other"),
    ("sv", "100", 0, "other"),
    ("sv", "1000", 0, "other"),
    ("sv", "10000", 0, "other"),
    ("sv", "100000", 0, "other"),
    ("sv", "1000000", 0, "other"),
    ("hi", "1", 0, "one"),
    ("hi", "2", 0, "two"),
    ("hi", "3", 0, "two"),
    ("hi", "4", 0, "few"),
    ("hi", "6", 0, "many"),
    ("hi", "0", 0, "other"),
    ("hi", "5", 0, "other"),
    ("hi", "7", 0, "other"),
    ("hi", "20", 0, "other"),
    ("hi", "100", 0, "other"),
    ("hi", "1000", 0, "other"),
    ("hi", "10000", 0, "other"),
    ("hi", "100000", 0, "other"),
    ("hi", "1000000", 0, "other"),
];

#[cfg(test)]
mod tests {
    #[test]
    fn cldr_48_official_plural_samples() {
        for &(lang, decimal, exponent, expected) in super::CARDINAL_SAMPLES {
            assert_eq!(super::select_cardinal(lang, decimal, exponent), expected, "cardinal {lang} {decimal}c{exponent}");
        }
        for &(lang, decimal, exponent, expected) in super::ORDINAL_SAMPLES {
            assert_eq!(super::select_ordinal(lang, decimal, exponent), expected, "ordinal {lang} {decimal}c{exponent}");
        }
    }
}
