// @generated by scripts/gen-regexp-native-harness.py; do not edit by hand.
// The generator's --check mode is the stale-file gate for this corpus.

#[test]
fn generated_one_byte_native_instruction_corpus() {
    let cases: &[(&str, &[&str])] = &[
        ("a.c", &["char", "any", "char"]),
        ("a+", &["many_char"]),
        ("a+?", &["many_char"]),
        ("[a-z]+", &["many_class"]),
        ("\\d{2,4}", &["many_class"]),
        (".*", &["many_any"]),
        ("^a.c$", &["start", "char", "any", "char", "end"]),
        ("a.c$", &["char", "any", "char", "end"]),
        ("[a-z].", &["class", "any"]),
        ("[^a].", &["class", "any"]),
        ("\\d[a-z]", &["class", "class"]),
        ("\\w\\s.", &["class", "class", "any"]),
        ("[A-Cx-z]0", &["class", "char"]),
        ("[\\x80-\\xff]é", &["class", "char"]),
        ("é.", &["char", "any"]),
        ("[\\0-\\x7f][^\\n]", &["class", "class"]),
    ];
    let subjects: &[&[u8]] = &[
        b"", b"a", b"aXc", b"xxaXcyy", b"a\nc", b"a\rc",
        b"0a", b"za", b"_9", b"!a", &[0x80, 0xe9, 0xff],
    ];
    let control = crate::RuntimeInterrupt::default();
    for &(pattern, expected_kinds) in cases {
        for &subject in subjects {
            for sticky in [false, true] {
                let flags = if sticky { "y" } else { "" };
                let re = super::Regex::new(pattern, flags).unwrap();
                let native = super::OneByteNativeProgram::compile(&re.prog, re.multiline)
                    .expect("generated subset case must compile");
                assert_eq!(native.ops.len(), expected_kinds.len(), "/{pattern}/");
                for ((instruction, op), expected) in re.prog[1..re.prog.len() - 2]
                    .iter()
                    .zip(native.ops.iter())
                    .zip(expected_kinds.iter())
                {
                    let actual = match instruction {
                        super::Inst::Char(_) => "char",
                        super::Inst::Any => "any",
                        super::Inst::Class(_) => "class",
                        super::Inst::AssertStart => "start",
                        super::Inst::AssertEnd => "end",
                        super::Inst::Many { rep, .. } => match rep {
                            super::Rep::Char(_) => "many_char",
                            super::Rep::Any => "many_any",
                            super::Rep::Class(_) => "many_class",
                        },
                        _ => panic!("unexpected instruction in /{pattern}/"),
                    };
                    assert_eq!(actual, *expected, "/{pattern}/");
                    for byte in 0..=u8::MAX {
                        let reference = match instruction {
                            super::Inst::Char(c) => *c == byte as u32,
                            super::Inst::Any => !super::is_line_terminator_u32(byte as u32),
                            super::Inst::Class(class) => class.matches(byte as u32, false, false),
                            super::Inst::AssertStart | super::Inst::AssertEnd => true,
                            super::Inst::Many { rep, .. } => match rep {
                                super::Rep::Char(c) => *c == byte as u32,
                                super::Rep::Any => !super::is_line_terminator_u32(byte as u32),
                                super::Rep::Class(class) => class.matches(byte as u32, false, false),
                            },
                            _ => unreachable!(),
                        };
                        assert_eq!(op.matches(byte as u32), reference,
                            "predicate mismatch for /{pattern}/ byte {byte}");
                    }
                }
                for start in 0..=subject.len() {
                    let fast = native.find(subject, start, sticky, &control);
                    let reference = re.find_impl(subject, start, &control);
                    assert_eq!(fast, reference,
                        "search mismatch for /{pattern}/ at {start}, sticky={sticky}, subject={subject:?}");
                }
            }
        }
    }
}
