#!/usr/bin/env python3
"""Generate DateTimeFormat patterns and field names for every advertised Lumen locale.

The source is CLDR 48's Gregorian calendar data. UTS #35 specifies that non-Gregorian calendars
inherit time patterns from Gregorian and general date patterns through the generic/Gregorian
fallback chain, so these locale pattern tables are also the base for Lumen's other calendars.
"""

from __future__ import annotations

import json
import pathlib
import urllib.request


TAG = "48.0.0"
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "crates/lumen/src/cldr_datetime_patterns.rs"
BASE = (
    f"https://raw.githubusercontent.com/unicode-org/cldr-json/{TAG}/"
    "cldr-json/cldr-dates-full/main"
)
LOCALES = [
    "en", "en-IN", "de", "fr", "es", "it", "pt", "pt-PT", "nl", "ja",
    "zh", "zh-Hant", "ko", "ru", "ar", "sr", "th", "gv", "sl", "pl",
    "si", "ln", "sv", "hi",
]
STYLE_NAMES = ["full", "long", "medium", "short"]
WEEKDAY_KEYS = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"]


def download(locale: str) -> dict:
    url = f"{BASE}/{locale}/ca-gregorian.json"
    request = urllib.request.Request(
        url, headers={"User-Agent": "Lumen CLDR DateTimeFormat generator"}
    )
    with urllib.request.urlopen(request) as response:
        return json.load(response)["main"][locale]["dates"]["calendars"]["gregorian"]


def rust_string(value: str) -> str:
    rendered = json.dumps(value, ensure_ascii=False)
    for character in ("\u200b", "\u2060", "\ufeff"):
        rendered = rendered.replace(character, f"\\u{{{ord(character):x}}}")
    return rendered


def ident(prefix: str, locale: str) -> str:
    return prefix + "_" + "".join(
        character.upper() if character.isalnum() else "_" for character in locale
    )


def ordinary_patterns(values: dict) -> list[tuple[str, str]]:
    rows = []
    for key, pattern in values.items():
        if "-alt-" in key or "-count-" in key or not isinstance(pattern, str):
            continue
        rows.append((key, pattern))
    return sorted(rows)


def default_hour_cycle(pattern: str) -> str:
    quoted = False
    for character in pattern:
        if character == "'":
            quoted = not quoted
        elif not quoted and character in "hHKk":
            return {"h": "h12", "K": "h11", "H": "h23", "k": "h24"}[character]
    return "h23"


def main() -> None:
    styles: dict[str, tuple[list[str], list[str], list[str], str]] = {}
    available: dict[str, list[tuple[str, str]]] = {}
    intervals: dict[str, list[tuple[str, str, str]]] = {}
    weekdays: dict[str, list[tuple[str, str, str]]] = {}
    day_periods: dict[str, list[tuple[str, str, str]]] = {}

    for locale in LOCALES:
        calendar = download(locale)
        date = [calendar["dateFormats"][style] for style in STYLE_NAMES]
        time = [calendar["timeFormats"][style] for style in STYLE_NAMES]
        date_time = calendar["dateTimeFormats"]
        # UTS #35's date+time combination uses the at-time alternative when present.  The
        # ordinary dateTimeFormats values remain the fallback inherited by locales without it.
        at_time = calendar.get("dateTimeFormats-atTime", {}).get("standard", date_time)
        connector = [at_time[style] for style in STYLE_NAMES]
        interval_data = date_time["intervalFormats"]
        styles[locale] = (date, time, connector, interval_data["intervalFormatFallback"])
        available[locale] = ordinary_patterns(date_time["availableFormats"])

        interval_rows = []
        for skeleton, by_difference in interval_data.items():
            if skeleton == "intervalFormatFallback" or not isinstance(by_difference, dict):
                continue
            for difference, pattern in by_difference.items():
                if isinstance(pattern, str):
                    interval_rows.append((skeleton, difference, pattern))
        intervals[locale] = sorted(interval_rows)

        weekday_rows = []
        format_days = calendar["days"]["format"]
        for width, key in (("long", "wide"), ("short", "abbreviated"), ("narrow", "narrow")):
            names = format_days[key]
            for day in WEEKDAY_KEYS:
                weekday_rows.append((width, day, names[day]))
        weekdays[locale] = sorted(weekday_rows)

        period_rows = []
        periods = calendar["dayPeriods"]["format"]
        for width, key in (("long", "wide"), ("short", "abbreviated"), ("narrow", "narrow")):
            for name, value in periods[key].items():
                if isinstance(value, str) and "-alt-" not in name:
                    period_rows.append((width, name, value))
        day_periods[locale] = sorted(period_rows)

    output = [
        "//! GENERATED by scripts/gen-cldr-datetime-patterns.py from CLDR 48. Do not edit.",
        "",
        "#[derive(Clone, Copy)]",
        "pub(crate) struct Styles {",
        "    dates: [&'static str; 4],",
        "    times: [&'static str; 4],",
        "    connectors: [&'static str; 4],",
        "    hour_cycle: &'static str,",
        "    pub fallback: &'static str,",
        "}",
        "",
    ]
    for locale in LOCALES:
        date, time, connector, fallback = styles[locale]
        output.extend(
            [
                f"static {ident('ST', locale)}: Styles = Styles {{",
                "    dates: [" + ", ".join(map(rust_string, date)) + "],",
                "    times: [" + ", ".join(map(rust_string, time)) + "],",
                "    connectors: [" + ", ".join(map(rust_string, connector)) + "],",
                f"    hour_cycle: {rust_string(default_hour_cycle(time[3]))},",
                f"    fallback: {rust_string(fallback)},",
                "};",
                "",
            ]
        )
        for prefix, rows in (
            ("AV", available[locale]),
            ("IV", intervals[locale]),
            ("WD", weekdays[locale]),
            ("DP", day_periods[locale]),
        ):
            arity = len(rows[0]) if rows else (2 if prefix == "AV" else 3)
            output.extend(
                [
                    "#[rustfmt::skip]",
                    f"static {ident(prefix, locale)}: &[({', '.join(['&str'] * arity)})] = &[",
                ]
            )
            for row in rows:
                output.append("    (" + ", ".join(map(rust_string, row)) + "),")
            output.extend(["];", ""])

    def locale_match(prefix: str) -> list[str]:
        return [f'        "{locale}" => {ident(prefix, locale)},' for locale in LOCALES]

    output.extend(
        [
            "pub(crate) fn locale(lang: &str, script: &str, region: &str) -> &'static str {",
            "    match (lang, script, region) {",
            '        ("en", _, "IN") => "en-IN",',
            '        ("pt", _, "PT") => "pt-PT",',
            '        ("zh", "Hant", _) | ("zh", _, "TW" | "HK" | "MO") => "zh-Hant",',
            "        _ => match lang {",
        ]
    )
    for locale in LOCALES:
        if "-" not in locale:
            output.append(f'            "{locale}" => "{locale}",')
    output.extend(['            _ => "en",', "        },", "    }", "}", ""])

    output.extend(["fn styles(locale: &str) -> Styles {", "    match locale {"])
    output.extend(locale_match("ST"))
    output.extend(["        _ => ST_EN,", "    }", "}", ""])

    output.extend(
        [
            "fn style_index(style: &str) -> usize {",
            '    match style { "full" => 0, "long" => 1, "medium" => 2, _ => 3 }',
            "}",
            "",
            "pub(crate) fn date_style(locale: &str, style: &str) -> &'static str {",
            "    styles(locale).dates[style_index(style)]",
            "}",
            "",
            "pub(crate) fn time_style(locale: &str, style: &str) -> &'static str {",
            "    styles(locale).times[style_index(style)]",
            "}",
            "",
            "pub(crate) fn connector(locale: &str, style: &str) -> &'static str {",
            "    styles(locale).connectors[style_index(style)]",
            "}",
            "",
            "pub(crate) fn range_fallback(locale: &str) -> &'static str { styles(locale).fallback }",
            "pub(crate) fn default_hour_cycle(locale: &str) -> &'static str { styles(locale).hour_cycle }",
            "",
            "fn available_rows(locale: &str) -> &'static [(&'static str, &'static str)] {",
            "    match locale {",
        ]
    )
    output.extend(locale_match("AV"))
    output.extend(["        _ => AV_EN,", "    }", "}", ""])
    output.extend(
        [
            "pub(crate) fn available(locale: &str) -> &'static [(&'static str, &'static str)] {",
            "    available_rows(locale)",
            "}",
            "",
            "pub(crate) fn available_exact(locale: &str, skeleton: &str) -> Option<&'static str> {",
            "    let rows = available_rows(locale);",
            "    rows.binary_search_by_key(&skeleton, |row| row.0).ok().map(|index| rows[index].1)",
            "}",
            "",
            "fn interval_rows(locale: &str) -> &'static [(&'static str, &'static str, &'static str)] {",
            "    match locale {",
        ]
    )
    output.extend(locale_match("IV"))
    output.extend(["        _ => IV_EN,", "    }", "}", ""])
    output.extend(
        [
            "pub(crate) fn interval(locale: &str, skeleton: &str, difference: &str) -> Option<&'static str> {",
            "    let rows = interval_rows(locale);",
            "    rows.binary_search_by(|row| row.0.cmp(skeleton).then_with(|| row.1.cmp(difference)))",
            "        .ok().map(|index| rows[index].2)",
            "}",
            "",
            "fn weekday_rows(locale: &str) -> &'static [(&'static str, &'static str, &'static str)] {",
            "    match locale {",
        ]
    )
    output.extend(locale_match("WD"))
    output.extend(["        _ => WD_EN,", "    }", "}", ""])
    output.extend(
        [
            "pub(crate) fn weekday(locale: &str, width: &str, day: &str) -> Option<&'static str> {",
            "    let rows = weekday_rows(locale);",
            "    rows.binary_search_by(|row| row.0.cmp(width).then_with(|| row.1.cmp(day)))",
            "        .ok().map(|index| rows[index].2)",
            "}",
            "",
            "fn period_rows(locale: &str) -> &'static [(&'static str, &'static str, &'static str)] {",
            "    match locale {",
        ]
    )
    output.extend(locale_match("DP"))
    output.extend(["        _ => DP_EN,", "    }", "}", ""])
    output.extend(
        [
            "pub(crate) fn day_period(locale: &str, width: &str, period: &str) -> Option<&'static str> {",
            "    let rows = period_rows(locale);",
            "    rows.binary_search_by(|row| row.0.cmp(width).then_with(|| row.1.cmp(period)))",
            "        .ok().map(|index| rows[index].2)",
            "}",
            "",
        ]
    )
    OUTPUT.write_text("\n".join(output), encoding="utf-8")
    print(
        f"wrote {OUTPUT} ({sum(map(len, available.values()))} skeletons, "
        f"{sum(map(len, intervals.values()))} interval patterns)"
    )


if __name__ == "__main__":
    main()
