#!/usr/bin/env python3
"""Generate UAX #29 segmentation property tables from Unicode 17.0.0.

Sources are the authoritative Unicode Character Database files named by UAX #29 and UAX #41:
  https://www.unicode.org/Public/17.0.0/ucd/auxiliary/{Grapheme,Word,Sentence}BreakProperty.txt
  https://www.unicode.org/Public/17.0.0/ucd/DerivedCoreProperties.txt
  https://www.unicode.org/Public/17.0.0/ucd/emoji/emoji-data.txt

The generated Rust uses one sorted interval table per property and binary search at runtime. This
keeps the complete Unicode data considerably smaller and faster than hash-based code-point maps.
"""

from __future__ import annotations

import pathlib
import re
import urllib.request


VERSION = "17.0.0"
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "crates/lumen/src/unicode_segment.rs"
UCD = f"https://www.unicode.org/Public/{VERSION}/ucd"

SOURCES = {
    "grapheme": f"{UCD}/auxiliary/GraphemeBreakProperty.txt",
    "word": f"{UCD}/auxiliary/WordBreakProperty.txt",
    "sentence": f"{UCD}/auxiliary/SentenceBreakProperty.txt",
    "derived": f"{UCD}/DerivedCoreProperties.txt",
    "emoji": f"{UCD}/emoji/emoji-data.txt",
}

PROPERTY_RE = re.compile(
    r"^\s*([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([A-Za-z_]+)(?:\s*;\s*([A-Za-z_]+))?"
)


def download(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": "Lumen Unicode table generator"})
    with urllib.request.urlopen(request) as response:
        return response.read().decode("utf-8")


def parse(text: str, property_name: str | None = None) -> list[tuple[int, int, str]]:
    ranges: list[tuple[int, int, str]] = []
    for line in text.splitlines():
        match = PROPERTY_RE.match(line)
        if not match:
            continue
        first, last, prop, value = match.groups()
        if property_name is not None:
            if prop != property_name:
                continue
            prop = value or "None"
        ranges.append((int(first, 16), int(last or first, 16), prop))
    ranges.sort()
    merged: list[tuple[int, int, str]] = []
    for first, last, prop in ranges:
        if merged and merged[-1][2] == prop and merged[-1][1] + 1 == first:
            previous = merged[-1]
            merged[-1] = (previous[0], last, prop)
        else:
            merged.append((first, last, prop))
    return merged


def rust_name(name: str) -> str:
    return "".join(piece.title() for piece in name.split("_"))


def emit_property(
    output: list[str],
    enum_name: str,
    function_name: str,
    constant_name: str,
    ranges: list[tuple[int, int, str]],
) -> None:
    values = sorted({prop for _, _, prop in ranges})
    output.extend(
        [
            "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
            f"pub(crate) enum {enum_name} {{",
            "    Other,",
        ]
    )
    for value in values:
        if value != "Other":
            output.append(f"    {rust_name(value)},")
    output.extend(["}", "", f"const {constant_name}: &[(u32, u32, {enum_name})] = &["])
    for first, last, value in ranges:
        if value == "Other":
            continue
        output.append(
            f"    (0x{first:X}, 0x{last:X}, {enum_name}::{rust_name(value)}),"
        )
    output.extend(
        [
            "];",
            "",
            f"pub(crate) fn {function_name}(code_point: u32) -> {enum_name} {{",
            f"    range_value({constant_name}, code_point).unwrap_or({enum_name}::Other)",
            "}",
            "",
        ]
    )


def main() -> None:
    source = {name: download(url) for name, url in SOURCES.items()}
    grapheme = parse(source["grapheme"])
    word = parse(source["word"])
    sentence = parse(source["sentence"])
    incb = parse(source["derived"], "InCB")
    pictographic = [entry for entry in parse(source["emoji"]) if entry[2] == "Extended_Pictographic"]

    output = [
        "//! GENERATED by scripts/gen-unicode-segment.py from Unicode 17.0.0. Do not edit.",
        "//!",
        "//! Complete UAX #29 Grapheme_Cluster_Break, Word_Break, Sentence_Break,",
        "//! Indic_Conjunct_Break, and Extended_Pictographic interval tables.",
        "",
        "fn range_value<T: Copy>(ranges: &[(u32, u32, T)], code_point: u32) -> Option<T> {",
        "    ranges",
        "        .binary_search_by(|&(first, last, _)| {",
        "            if code_point < first {",
        "                std::cmp::Ordering::Greater",
        "            } else if code_point > last {",
        "                std::cmp::Ordering::Less",
        "            } else {",
        "                std::cmp::Ordering::Equal",
        "            }",
        "        })",
        "        .ok()",
        "        .map(|index| ranges[index].2)",
        "}",
        "",
    ]
    emit_property(output, "GraphemeBreak", "grapheme_break", "GRAPHEME_BREAK", grapheme)
    emit_property(output, "WordBreak", "word_break", "WORD_BREAK", word)
    emit_property(output, "SentenceBreak", "sentence_break", "SENTENCE_BREAK", sentence)
    emit_property(output, "IndicConjunctBreak", "indic_conjunct_break", "INDIC_CONJUNCT_BREAK", incb)

    output.append("const EXTENDED_PICTOGRAPHIC: &[(u32, u32)] = &[")
    for first, last, _ in pictographic:
        output.append(f"    (0x{first:X}, 0x{last:X}),")
    output.extend(
        [
            "];",
            "",
            "pub(crate) fn is_extended_pictographic(code_point: u32) -> bool {",
            "    EXTENDED_PICTOGRAPHIC",
            "        .binary_search_by(|&(first, last)| {",
            "            if code_point < first {",
            "                std::cmp::Ordering::Greater",
            "            } else if code_point > last {",
            "                std::cmp::Ordering::Less",
            "            } else {",
            "                std::cmp::Ordering::Equal",
            "            }",
            "        })",
            "        .is_ok()",
            "}",
            "",
        ]
    )
    OUTPUT.write_text("\n".join(output), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(output)} lines)")


if __name__ == "__main__":
    main()
