#!/usr/bin/env python3
"""Generate localized calendar month and era names for Intl.DateTimeFormat.

The tables cover every locale advertised by Lumen and every calendar accepted by its
DateTimeFormat implementation. Data is partitioned by locale so lookups stay logarithmic within a
small slice instead of scanning one global table.
"""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
import json
import pathlib
import urllib.request


TAG = "48.0.0"
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "crates/lumen/src/cldr_dates.rs"
RAW = f"https://raw.githubusercontent.com/unicode-org/cldr-json/{TAG}/cldr-json"
LOCALES = [
    "en", "en-IN", "de", "fr", "es", "it", "pt", "pt-PT", "nl", "ja",
    "zh", "zh-Hant", "ko", "ru", "ar", "sr", "th", "gv", "sl", "pl",
    "si", "ln", "sv", "hi",
]
# (Lumen calendar id, CLDR package, file id, key inside dates.calendars)
CALENDARS = [
    ("gregory", "cldr-dates-full", "gregorian", "gregorian"),
    ("buddhist", "cldr-cal-buddhist-full", "buddhist", "buddhist"),
    ("chinese", "cldr-cal-chinese-full", "chinese", "chinese"),
    ("coptic", "cldr-cal-coptic-full", "coptic", "coptic"),
    ("dangi", "cldr-cal-dangi-full", "dangi", "dangi"),
    ("ethioaa", "cldr-cal-ethiopic-full", "ethiopic-amete-alem", "ethiopic-amete-alem"),
    ("ethiopic", "cldr-cal-ethiopic-full", "ethiopic", "ethiopic"),
    ("hebrew", "cldr-cal-hebrew-full", "hebrew", "hebrew"),
    ("indian", "cldr-cal-indian-full", "indian", "indian"),
    ("islamic", "cldr-cal-islamic-full", "islamic", "islamic"),
    ("islamic-civil", "cldr-cal-islamic-full", "islamic-civil", "islamic-civil"),
    ("islamic-tbla", "cldr-cal-islamic-full", "islamic-tbla", "islamic-tbla"),
    ("islamic-umalqura", "cldr-cal-islamic-full", "islamic-umalqura", "islamic-umalqura"),
    ("japanese", "cldr-cal-japanese-full", "japanese", "japanese"),
    ("persian", "cldr-cal-persian-full", "persian", "persian"),
    ("roc", "cldr-cal-roc-full", "roc", "roc"),
]


def rust_string(value: str) -> str:
    rendered = json.dumps(value, ensure_ascii=False)
    for character in ("\u200b", "\u2060", "\ufeff"):
        rendered = rendered.replace(character, f"\\u{{{ord(character):x}}}")
    return rendered


def ident(prefix: str, locale: str) -> str:
    return prefix + "_" + "".join(
        character.upper() if character.isalnum() else "_" for character in locale
    )


def download(task: tuple[str, tuple[str, str, str, str]]) -> tuple[str, str, dict]:
    locale, (calendar, package, file_id, data_key) = task
    url = f"{RAW}/{package}/main/{locale}/ca-{file_id}.json"
    request = urllib.request.Request(
        url, headers={"User-Agent": "Lumen CLDR calendar-name generator"}
    )
    with urllib.request.urlopen(request) as response:
        root = json.load(response)["main"][locale]["dates"]["calendars"]
    return locale, calendar, root[data_key]


def main() -> None:
    months: dict[str, list[tuple[str, str, int, str]]] = {locale: [] for locale in LOCALES}
    eras: dict[str, list[tuple[str, str, str, str]]] = {locale: [] for locale in LOCALES}
    tasks = [(locale, calendar) for locale in LOCALES for calendar in CALENDARS]
    with ThreadPoolExecutor(max_workers=16) as pool:
        results = list(pool.map(download, tasks))
    for locale, calendar, data in results:
        month_data = data.get("months", {}).get("format", {})
        for width, cldr_width in (("long", "wide"), ("short", "abbreviated"), ("narrow", "narrow")):
            for month, value in month_data.get(cldr_width, {}).items():
                if isinstance(value, str) and month.isdigit():
                    months[locale].append((calendar, width, int(month), value))
        era_data = data.get("eras", {})
        for width, cldr_width in (("long", "eraNames"), ("short", "eraAbbr"), ("narrow", "eraNarrow")):
            for era, value in era_data.get(cldr_width, {}).items():
                if isinstance(value, str) and "-alt-" not in era:
                    eras[locale].append((calendar, width, era, value))

    output = [
        "//! GENERATED by scripts/gen-cldr-dates.py from CLDR 48. Do not edit.",
        "",
    ]
    for locale in LOCALES:
        month_rows = sorted(set(months[locale]))
        era_rows = sorted(set(eras[locale]))
        output.extend([
            "#[rustfmt::skip]",
            f"static {ident('MO', locale)}: &[(&str, &str, u8, &str)] = &[",
        ])
        for calendar, width, month, value in month_rows:
            output.append(
                f"    ({rust_string(calendar)}, {rust_string(width)}, {month}, {rust_string(value)}),"
            )
        output.extend([
            "];",
            "#[rustfmt::skip]",
            f"static {ident('ER', locale)}: &[(&str, &str, &str, &str)] = &[",
        ])
        for calendar, width, era, value in era_rows:
            output.append(
                f"    ({rust_string(calendar)}, {rust_string(width)}, {rust_string(era)}, {rust_string(value)}),"
            )
        output.extend(["];", ""])

    output.extend([
        "fn month_rows(locale: &str) -> &'static [(&'static str, &'static str, u8, &'static str)] {",
        "    match locale {",
    ])
    for locale in LOCALES:
        output.append(f'        "{locale}" => {ident("MO", locale)},')
    output.extend(["        _ => MO_EN,", "    }", "}", ""])
    output.extend([
        "fn era_rows(locale: &str) -> &'static [(&'static str, &'static str, &'static str, &'static str)] {",
        "    match locale {",
    ])
    for locale in LOCALES:
        output.append(f'        "{locale}" => {ident("ER", locale)},')
    output.extend(["        _ => ER_EN,", "    }", "}", ""])
    output.extend([
        "/// The month name (1-based) for a locale/calendar/width, if shipped.",
        "pub fn month_name(locale: &str, calendar: &str, width: &str, month: u8) -> Option<&'static str> {",
        "    let rows = month_rows(locale);",
        "    rows.binary_search_by(|row| (row.0, row.1, row.2).cmp(&(calendar, width, month)))",
        "        .ok().map(|index| rows[index].3)",
        "}",
        "",
        "/// The era name for a locale/calendar/width/era-key, if shipped.",
        "pub fn era_name(locale: &str, calendar: &str, width: &str, era: &str) -> Option<&'static str> {",
        "    let rows = era_rows(locale);",
        "    rows.binary_search_by(|row| (row.0, row.1, row.2).cmp(&(calendar, width, era)))",
        "        .ok().map(|index| rows[index].3)",
        "}",
        "",
    ])
    OUTPUT.write_text("\n".join(output), encoding="utf-8")


if __name__ == "__main__":
    main()
