#!/usr/bin/env python3
"""Generate RelativeTimeFormat phrases/patterns from CLDR 48 resolved date fields.

Source: unicode-org/cldr-json 48.0.0, cldr-dates-full/main/*/dateFields.json.
Tables are sorted and binary-searched, keeping the complete advertised-locale data compact without
runtime parsing, hashing, or allocation.
"""

from __future__ import annotations

import json
import pathlib
import urllib.request


TAG = "48.0.0"
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "crates/lumen/src/cldr_relative_time.rs"
BASE = (
    f"https://raw.githubusercontent.com/unicode-org/cldr-json/{TAG}/"
    "cldr-json/cldr-dates-full/main"
)
LOCALES = [
    "en", "de", "fr", "es", "it", "pt", "nl", "ja", "zh", "ko", "ru", "ar",
    "sr", "th", "gv", "sl", "pl", "si", "ln", "sv", "hi",
]
UNITS = ["year", "quarter", "month", "week", "day", "hour", "minute", "second"]
STYLES = ["long", "short", "narrow"]


def download(locale: str) -> dict:
    url = f"{BASE}/{locale}/dateFields.json"
    request = urllib.request.Request(url, headers={"User-Agent": "Lumen CLDR relative-time generator"})
    with urllib.request.urlopen(request) as response:
        return json.load(response)["main"][locale]["dates"]["fields"]


def rust_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    automatic = []
    patterns = []
    for locale in LOCALES:
        fields = download(locale)
        for unit in UNITS:
            for style in STYLES:
                key = unit if style == "long" else f"{unit}-{style}"
                field = fields[key]
                for name, phrase in field.items():
                    if name.startswith("relative-type-"):
                        value = int(name.removeprefix("relative-type-"))
                        automatic.append((locale, unit, style, value, phrase))
                for tense in ("past", "future"):
                    group = field[f"relativeTime-type-{tense}"]
                    for name, pattern in group.items():
                        category = name.removeprefix("relativeTimePattern-count-")
                        if pattern.count("{0}") > 1:
                            raise RuntimeError(f"{locale}/{key}/{tense}/{category}: {pattern!r}")
                        patterns.append((locale, unit, style, tense, category, pattern))

    automatic.sort(key=lambda row: row[:-1])
    patterns.sort(key=lambda row: row[:-1])
    output = [
        "//! GENERATED by scripts/gen-cldr-relative-time.py from CLDR 48. Do not edit.",
        "",
        "const AUTO: &[(&str, &str, &str, i8, &str)] = &[",
    ]
    for locale, unit, style, value, phrase in automatic:
        output.append(
            f'    ("{locale}", "{unit}", "{style}", {value}, {rust_string(phrase)}),'
        )
    output.extend(["];", "", "const PATTERNS: &[(&str, &str, &str, &str, &str, &str)] = &["])
    for locale, unit, style, tense, category, pattern in patterns:
        output.append(
            f'    ("{locale}", "{unit}", "{style}", "{tense}", "{category}", {rust_string(pattern)}),'
        )
    output.extend(
        [
            "];",
            "",
            "pub(crate) fn auto(lang: &str, unit: &str, style: &str, value: i8) -> Option<&'static str> {",
            "    AUTO.binary_search_by(|&(l, u, s, v, _)| (l, u, s, v).cmp(&(lang, unit, style, value)))",
            "        .ok().map(|index| AUTO[index].4)",
            "}",
            "",
            "fn exact_pattern(lang: &str, unit: &str, style: &str, tense: &str, category: &str) -> Option<&'static str> {",
            "    PATTERNS.binary_search_by(|&(l, u, s, t, c, _)|",
            "        (l, u, s, t, c).cmp(&(lang, unit, style, tense, category)))",
            "        .ok().map(|index| PATTERNS[index].5)",
            "}",
            "",
            "pub(crate) fn pattern(lang: &str, unit: &str, style: &str, tense: &str, category: &str) -> Option<&'static str> {",
            "    exact_pattern(lang, unit, style, tense, category)",
            "        .or_else(|| exact_pattern(lang, unit, style, tense, \"other\"))",
            "}",
            "",
        ]
    )
    OUTPUT.write_text("\n".join(output), encoding="utf-8")
    print(
        f"wrote {OUTPUT.relative_to(ROOT)} ({len(automatic)} auto phrases, {len(patterns)} patterns)"
    )


if __name__ == "__main__":
    main()
