#!/usr/bin/env python3
"""Generate Intl.ListFormat patterns for every locale Lumen advertises from CLDR 48.

Source: unicode-org/cldr-json 48.0.0, cldr-misc-full/main/*/listPatterns.json. The
output groups locales with identical pattern sets and uses direct match dispatch at runtime.
"""

from __future__ import annotations

import json
import pathlib
import urllib.request


TAG = "48.0.0"
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "crates/lumen/src/cldr_lists.rs"
BASE = (
    f"https://raw.githubusercontent.com/unicode-org/cldr-json/{TAG}/"
    "cldr-json/cldr-misc-full/main"
)
LOCALES = [
    "en", "de", "fr", "es", "it", "pt", "nl", "ja", "zh", "ko", "ru", "ar",
    "sr", "th", "gv", "sl", "pl", "si", "ln", "sv", "hi",
]
KINDS = {"conjunction": "standard", "disjunction": "or", "unit": "unit"}
STYLES = ["long", "short", "narrow"]


def download(locale: str) -> dict:
    url = f"{BASE}/{locale}/listPatterns.json"
    request = urllib.request.Request(url, headers={"User-Agent": "Lumen CLDR list generator"})
    with urllib.request.urlopen(request) as response:
        return json.load(response)["main"][locale]["listPatterns"]


def rust_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    rows = []
    for locale in LOCALES:
        data = download(locale)
        for kind, cldr_kind in KINDS.items():
            for style in STYLES:
                suffix = "" if style == "long" else f"-{style}"
                pattern = data[f"listPattern-type-{cldr_kind}{suffix}"]
                values = tuple(pattern[key] for key in ("2", "start", "middle", "end"))
                for value in values:
                    if value.count("{0}") != 1 or value.count("{1}") != 1:
                        raise RuntimeError(f"{locale}/{kind}/{style}: invalid pattern {value!r}")
                    if value.index("{0}") > value.index("{1}"):
                        raise RuntimeError(f"{locale}/{kind}/{style}: reversed placeholders")
                rows.append((locale, kind, style, values))

    output = [
        "//! GENERATED by scripts/gen-cldr-lists.py from CLDR 48. Do not edit.",
        "//! Pair, start, middle, and end patterns for each locale/type/style Lumen supports.",
        "",
        "pub(crate) fn patterns(lang: &str, kind: &str, style: &str) -> [&'static str; 4] {",
        "    match (lang, kind, style) {",
    ]
    for locale, kind, style, values in rows:
        rendered = ", ".join(rust_string(value) for value in values)
        output.append(f'        ("{locale}", "{kind}", "{style}") => [{rendered}],')
    output.extend(
        [
            "        _ => [\"{0} and {1}\", \"{0}, {1}\", \"{0}, {1}\", \"{0}, and {1}\"],",
            "    }",
            "}",
            "",
        ]
    )
    OUTPUT.write_text("\n".join(output), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(rows)} pattern sets)")


if __name__ == "__main__":
    main()
