#!/usr/bin/env python3
"""Generate the RegExp corpus timing harness from benchmarks/regexp-corpus/manifest.json.

The generated JS is self-verifying: every entry is probed once per subject from a fresh
RegExp, the match count is compared to the manifest's locked expectation (a divergence
prints MISMATCH and the final verdict is CORPUS FAIL / exit 3), and per-entry iterations
scale to ~40ms against the first subject so the corpus stays quick (~6s per engine).
Adversarial entries hard-cap their loops and treat engine step-budget termination as an
acceptable outcome (a match is still counted when one is expected).

  python3 scripts/gen-regexp-corpus.py harness <out.js>   # write the harness
  python3 scripts/gen-regexp-corpus.py lock               # write subjects_sha256 back
  python3 scripts/gen-regexp-corpus.py check              # verify pinned hashes only

The subjects_sha256 field locks the canonical compact-JSON array of each entry's subjects;
the harness generation refuses to run on a tampered manifest until `lock` restores it.
"""

import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "benchmarks" / "regexp-corpus" / "manifest.json"

VALID_CATEGORIES = {"fixture", "real-page", "conformance", "unicode", "adversarial"}


def canonical_subjects_hash(subjects):
    # ensure_ascii keeps lone-surrogate subjects byte-stable (JSON \uXXXX escapes) and the
    # hash independent of file encoding.
    payload = json.dumps(subjects, ensure_ascii=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def load_manifest(require_hash=True, strict_hash=True):
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if manifest.get("schema_version") != 1:
        raise SystemExit("manifest schema_version must be 1")
    ids = set()
    for entry in manifest["entries"]:
        if entry["id"] in ids:
            raise SystemExit(f"duplicate entry id {entry['id']}")
        ids.add(entry["id"])
        category = entry.get("category")
        if category not in VALID_CATEGORIES:
            raise SystemExit(f"entry {entry['id']}: invalid category {category}")
        if not isinstance(entry.get("subjects"), list) or not entry["subjects"]:
            raise SystemExit(f"entry {entry['id']}: need a non-empty subjects array")
        if not isinstance(entry.get("expected_matches"), int):
            raise SystemExit(f"entry {entry['id']}: expected_matches must be an int")
        if not 0 <= entry["expected_matches"] <= len(entry["subjects"]):
            raise SystemExit(f"entry {entry['id']}: expected_matches out of range")
        if not isinstance(entry.get("pattern"), str) or not entry["pattern"]:
            raise SystemExit(f"entry {entry['id']}: need a pattern")
        pinned = entry.get("subjects_sha256")
        actual = canonical_subjects_hash(entry["subjects"])
        if pinned is not None:
            if pinned != actual and strict_hash:
                raise SystemExit(
                    f"entry {entry['id']}: subjects_sha256 mismatch (run `lock` to re-pin)"
                )
        elif require_hash:
            raise SystemExit(f"entry {entry['id']}: subjects_sha256 missing (run `lock` first)")
    return manifest


def emit_harness(manifest, out_path):
    lines = [
        "// Generated by scripts/gen-regexp-corpus.py from benchmarks/regexp-corpus/manifest.json.",
        "// Self-verifying RegExp corpus: per-entry probe match counts must equal the locked",
        "// expectations, and per-entry iterations scale against the first subject.",
        'var log = typeof print === "function" ? print : function (s) { console.log(s); };',
        "",
        "var entries = [",
    ]
    for entry in manifest["entries"]:
        record = {
            "id": entry["id"],
            "pattern": entry["pattern"],
            "flags": entry.get("flags", ""),
            "subjects": entry["subjects"],
            "expected": entry["expected_matches"],
            "adversarial": entry["category"] == "adversarial",
        }
        lines.append(
            "  "
            + json.dumps(record, ensure_ascii=True, separators=(",", ":"))
            + ","
        )
    lines += [
        "];",
        "",
        "// Probe: fresh RegExp per subject; adversarial throws count as budget termination.",
        "function probe(entry) {",
        "  var matched = 0;",
        "  var budget = 0;",
        "  for (var j = 0; j < entry.subjects.length; j++) {",
        "    var re = new RegExp(entry.pattern, entry.flags);",
        "    if (entry.adversarial) {",
        "      try { if (re.exec(entry.subjects[j]) !== null) matched++; }",
        "      catch (error) { budget++; }",
        "    } else if (re.exec(entry.subjects[j]) !== null) {",
        "      matched++;",
        "    }",
        "  }",
        "  return [matched, budget];",
        "}",
        "",
        "// Timing: scale iterations against the first subject to ~40ms; adversarial",
        "// entries hard-cap at 3 reps so the step budget stays the termination guard.",
        "function timeIt(entry, probeRe) {",
        "  var reps = 1;",
        "  var ms = 0;",
        "  var maxReps = entry.adversarial ? 3 : 1 << 24;",
        "  for (var scale = 0; scale < 16 && ms < 40 && reps <= maxReps; scale++) {",
        "    var t0 = Date.now();",
        "    if (entry.adversarial) {",
        "      try {",
        "        for (var r = 0; r < reps; r++) probeRe.exec(entry.subjects[0]);",
        "      } catch (error) {}",
        "    } else {",
        "      for (var r = 0; r < reps; r++) probeRe.exec(entry.subjects[0]);",
        "    }",
        "    ms = Date.now() - t0;",
        "    if (ms < 40) { reps *= 4; }",
        "  }",
        "  return [reps, ms];",
        "}",
        "",
        "var ok = true;",
        "for (var i = 0; i < entries.length; i++) {",
        "  var entry = entries[i];",
        "  var probed = probe(entry);",
        "  var verdict = probed[0] === entry.expected ? \"OK\" : \"MISMATCH expected \" + entry.expected;",
        "  if (probed[0] !== entry.expected) ok = false;",
        "  var timed = timeIt(entry, new RegExp(entry.pattern, entry.flags));",
        "  log(entry.id + \" matches=\" + probed[0] + (probed[1] ? \" budget=\" + probed[1] : \"\")",
        "      + \" \" + verdict + \" reps=\" + timed[0] + \" ms=\" + timed[1]);",
        "}",
        "log(ok ? \"CORPUS OK\" : \"CORPUS FAIL\");",
        "if (!ok && typeof quit === \"function\") quit(3);",
        "",
    ]
    out = pathlib.Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")


def lock_manifest(force=False):
    manifest = load_manifest(require_hash=False, strict_hash=not force)
    changed = False
    for entry in manifest["entries"]:
        pinned = entry.get("subjects_sha256")
        actual = canonical_subjects_hash(entry["subjects"])
        if pinned != actual:
            if pinned is not None and not force:
                raise SystemExit(f"entry {entry['id']}: refusing to overwrite a mismatched pin (use lock --force)")
            entry["subjects_sha256"] = actual
            changed = True
    if changed:
        payload = json.dumps(manifest, ensure_ascii=True, indent=2) + "\n"
        # Build the payload before opening the file: an encoding failure must never truncate
        # the manifest (a previous ordering emptied it on a lone-surrogate input).
        MANIFEST.write_text(payload, encoding="utf-8")
        print(f"locked subject hashes in {MANIFEST}")
    else:
        print("manifest already locked")


def main():
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    mode = sys.argv[1]
    if mode == "harness":
        if len(sys.argv) != 3:
            raise SystemExit("usage: gen-regexp-corpus.py harness <out.js>")
        emit_harness(load_manifest(), sys.argv[2])
    elif mode == "lock":
        lock_manifest(force="--force" in sys.argv[2:])
    elif mode == "check":
        load_manifest()
        print("manifest hashes verified")
    else:
        raise SystemExit(f"unknown mode {mode}")


if __name__ == "__main__":
    main()